[gcp_service_account]
type = "service_account"
project_id = "plexiform-pilot-457607-k7"
private_key_id = "e48d55679cbaed5142799079be9ef27a33df2292"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC4G3ka6khy464w
eHZci4babv58PjNUdpHV+yhFRDywlQlc8RG1phcm3QtCI94GpNiAOaNMyt+/DgQG
JU7Ply0V/vFwT/WYtDjFI7HXxZLFvEFYY30ppFE/M+W0OLbwOV4iUF05cM4cWQq1
zu2vyaqB6ESzYRITGn6gr4r+dvbwPHZA++R92jbSLFw8jpVWgwveVrCSiaiFOH/X
0XNhvSxQ0tp0E3LS9FzE9xemNMAhGYFkjo1u1/82O7ubKLFBV1ZvVc/1x1FcTgkM
X0ZMZypW3NhX9nS0/84oO5x+Ev4uaF5SEtVlmdNI2jp6dob29a+hBhcQaNtd4gyo
g+DXMs3TAgMBAAECggEAHXWSmf1FvSc0HDVqWxdIa3Nkl+TWudEvN2+KMMCL0DBI
4JetHxqF4dtvjb8c1oX8zqe/uu32LNAap2ZuMfFyxBjt8UFvfxEiHwloelT2+K+i
6nh2R/ovC09L64aXtItkG1bYqUmk8WGeFnFsvxAkjxzna/yVs9DYKkYXQO3a8vMI
ye4ygJi0suVq4IuODPjE7/xJAJf/K6RHs7r2uy7c1dSSgauUBI/zkKSs/SpGV4gb
jSUnvG6ieZeAY5iEUec29kvnHxpmzUoobErYBU75SE8+EGwnnCNM+O4M/iCTvaqw
SscoiipXni5DZORAlPguwtYYl+HtfcTWZEojj9enwQKBgQD94L6dbJ+bLaBFt6yt
+L8DYD29p5fWHqyN+DmcaiqnjVMqolofuZFc22brIV+ktIh0h0goIU7QYeZ0L7TP
RHMwkpkZXynuuK+HT1NafCWW5D1EvZBdfHnHi4uE3hh8VGYYVRTMbNl83qMSMXho
dgKUV0KsS5y5MLZiIU2HKXDmSQKBgQC5pW5qm6XTgcxMA8PlI9tbYIug30SAtfKf
CQdCyG9EbezIodNa+QA9+COuDXWvSKuJAl0on/U1RMZv3jMDngV9YgWGHTvi5AsU
9s6O4bHOxR94RRkcY5SMWfQCGwJOViACFlQ9/qMx6haR1Jrn0tuD0+oAesiuqp+q
9NNGIiPjOwKBgQCAsB9vJNRykFohfM0nEmOgjnQ9YmpwuvO0sxJg2t/sNpLllY4h
bqrkasJshWo5ztksWDaXQOr2bemnE1ePiJ7rDCRW3AohW7R93hPeVfen2OHFqmE3
QhVotK9wFjRLMWzfAKGeTb6gsSnv2uux57+++cxuEZXLuYl5jHAEB1mXIQKBgQCj
7NTz495oReusj4KRubi/FiAU/DDT6lWDYoh7ytqdNOdpPaOQZ+Bz18FBtnbdQTDe
eSzja2MtFz6Vl0G6hvVYAo7YHsY7kZvLdidseRP1fZBNNc53h+Kqj99rYIgHvfrj
fO4EE+3sbERjnrTt0P2uiRfONp0vxk/Yt/g6rHi98wKBgQCHEbZAHv6GcZLatYuh
WL25Er5uhHBMOrgTTfW40Q7N33Lt57A3KknaQqNz3fmLV5Abz507qMRJoJOjGRNE
x7vPfe6SqcCSzGJ+M7gzauzzuAcg9p9MUxHECqXMN1pxIXh0deacQEASt6Hbin3V
lUd8SW/Ea6dvv0iq0DyQ2+vNiQ==
-----END PRIVATE KEY-----"""
client_email = "ffring-bot@plexiform-pilot-457607-k7.iam.gserviceaccount.com"
client_id = "117332811049376774571"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ffring-bot%40plexiform-pilot-457607-k7.iam.gserviceaccount.com"
